RightPath/Models/ApplicationUser.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;

namespace RightPath.Models
{
    public class ApplicationUser: IdentityUser
    {
        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }

        [Required]
        [StringLength(10)]
        public string EGN {  get; set; }

    }
}

RightPath/Areas/Admin/Controllers/ApplicationUserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RightPath.Data;
using RightPath.Models;
using RightPath.Repository;
using System.Data;

namespace RightPath.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = StaticDetail.Role_Admin)]
    public class ApplicationUserController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly UnitOfWork _unitOfWork;

        public ApplicationUserController(ApplicationDbContext  context, UserManager<ApplicationUser> userManager, UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _context = context;
            _userManager = userManager;
        }

        // GET: User
        public async Task<IActionResult> Index()
        {
            var users = await _context.ApplicationUsers.ToListAsync();
            var displayUsers = new List<ApplicationUser>();

            foreach (var user in users)
            {
                if (await _userManager.IsInRoleAsync(user, StaticDetail.Role_Lecture) || await _userManager.IsInRoleAsync(user, StaticDetail.Role_Customer))
                {
                    displayUsers.Add(user);
                }
            }

            return View(displayUsers);
        }

        // GET: User/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: User/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ApplicationUser model, string newPassword, string confirmPassword)
        {
                var user = await _userManager.FindByIdAsync(model.Id);

                if (user == null)
                {
                    return NotFound();
                }

                user.FirstName = model.FirstName;
                user.Email = model.Email;
                user.PhoneNumber = model.PhoneNumber;
                user.EGN = model.EGN;

                if (!string.IsNullOrEmpty(newPassword))
                {
                    if (newPassword != confirmPassword)
                    {
                        ModelState.AddModelError("PasswordHash", "Паролите не съвпадат.");
                        return View(model);
                    }

                    var passwordHash = _userManager.PasswordHasher.HashPassword(user, newPassword);
                    user.PasswordHash = passwordHash;
                }

                var result = await _userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            

            return View(model);
        }

        public IActionResult Delete(string id)
        {
            ApplicationUser user = _unitOfWork.ApplicationUser.Get(u => u.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            _unitOfWork.ApplicationUser.Remove(user);
            _unitOfWork.Save();
            TempData["success"] = "Потребителят е изтрит успешно!";
            return RedirectToAction("Index");
        }
    }
}

RightPath/Areas/Admin/Views/ApplicationUser/Edit.cshtml
@model ApplicationUser

<div class="container">
    <div class="spacer"></div>

    <h1>Редактирай потребител</h1>

    <form method="post">
        <div asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <label for="userFirstName" class="form-label mt-4">Име</label>
            <input asp-for="FirstName" type="text" class="form-control" id="userFirstName">
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="userEmail" class="form-label mt-4">Имейл</label>
            <input asp-for="Email" type="email" class="form-control" id="userEmail">
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="userEGN" class="form-label mt-4">ЕГН</label>
            <input asp-for="EGN" type="text" class="form-control" id="userEGN">
            <span asp-validation-for="EGN" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="userPhoneNumber" class="form-label mt-4">Телефонен Номер</label>
            <input asp-for="PhoneNumber" type="text" class="form-control" id="userPhoneNumber">
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="newPassword" class="control-label">Нова Парола</label>
            <input type="password" class="form-control" name="newPassword" id="newPassword" />
        </div>
        <div class="form-group">
            <label for="confirmPassword" class="control-label">Потвърди Паролата</label>
            <input type="password" class="form-control" name="confirmPassword" id="confirmPassword" />
        </div>
        <div class="mt-3">
            <button type="submit" class="btn btn-warning">Редактирай</button>
            <a asp-controller="ApplicationUser" asp-action="Index" class="btn btn-secondary">Обратно към потребителите</a>
        </div>

    </form>

</div>

RightPath/Areas/Admin/Views/ApplicationUser/Index.cshtml
@model List<ApplicationUser>

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-primary py-2">Потребители</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
            <div class="col-6 text-end">
                <a asp-area="Identity" asp-page="/Account/Register" class="btn btn-warning">
                    <i class="bi bi-plus-circle"></i> Добави нов Потребител
                </a>
            </div>
        </div>
        <table id="usersTable" class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Име</th>
                    <th>Имейл</th>
                    <th>Телефонен Номер</th>
                    <th>ЕГН</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.FirstName
                        </td>
                        <td>
                            @item.Email
                        </td>
                        <td>
                            @item.PhoneNumber
                        </td>
                        <td>
                            @item.EGN
                        </td>
                        <td>
                            <div class="btn-group badge" role="group">
                                @* Да направя нови изгледи за редактиране и за изтриване и да добавя функционалността във контролера*@
                                <a asp-controller="ApplicationUser" asp-action="Edit" asp-route-id="@item.Id" class="shadow btn btn-light mx-2 px-4">
                                    <i class="bi bi-pencil-square"></i> Редактирай
                                </a>
                                <a class="btn btn-danger mx-2 px-4" asp-controller="ApplicationUser" asp-action="Delete" asp-route-id="@item.Id">
                                    <i class="bi bi-trash-fill"></i> Изтрий
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>