RightPath/Areas/Admin/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RightPath.Models.ViewModel;
using RightPath.Data;
using RightPath.Models;
using RightPath.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;

namespace RightPath.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = StaticDetail.Role_Admin)]
    public class CoursesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public CoursesController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Webminars
        public IActionResult Index()
        {
            List<Course> objLectureList = _unitOfWork.Course.GetAll(includeProperties: "Lecture").ToList();
            return View(objLectureList);
        }

        // GET: Webminars/Create
        public IActionResult Upsert(int? id)
        {
            CourseVM courseVM = new()
            {
                LectureList = _unitOfWork.Lecture.GetAll().Select(y => new SelectListItem
                {
                    Text = y.Name,
                    Value = y.Id.ToString()
                }),
                Course = new Course()
            };

            if (id == null || id == 0)
            {
                //functionality for create
                return View(courseVM);
            }
            else
            {
                //functionality for edit
                courseVM.Course = _unitOfWork.Course.Get(u => u.Id == id);
                return View(courseVM);
            }
        }

        [HttpPost]
        public IActionResult Upsert(CourseVM courseVM, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRoothPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string productPath = Path.Combine(wwwRoothPath, @"images\products");

                    if (!string.IsNullOrEmpty(courseVM.Course.Logo))
                    {
                        //delete old image logic
                        var oldImagePath = Path.Combine(wwwRoothPath, courseVM.Course.Logo.TrimStart('\\'));

                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }

                    courseVM.Course.Logo = fileName;
                }

                if (courseVM.Course.Id == 0)
                {
                    _unitOfWork.Course.Add(courseVM.Course);
                    TempData["success"] = "Курсът е създаден успешно!";
                }
                else
                {
                    _unitOfWork.Course.Update(courseVM.Course);
                    TempData["success"] = "Курсът е редактиран успешно!";
                }
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View();

        }


        // POST: Webminars/Delete/5
        public IActionResult Delete(int id)
        {
            Course? obj = _unitOfWork.Course.Get(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.Course.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Уебминара е изтрит успешно!";
            return RedirectToAction("Index");
        }
    }
}

RightPath/Areas/Customer/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RightPath.Models;
using RightPath.Repository.IRepository;
using System.Security.Claims;

namespace RightPath.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class CartController : Controller
    {
        private IUnitOfWork _unitOfWork;
        public CartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ShoppingCart shoppingCart = _unitOfWork.ShoppingCart.Get(s => s.ApplicationUserId == userId, "Courses,Webminars");

            ViewBag.Courses = shoppingCart.Courses
                .Select(c => _unitOfWork.Course.Get(course => course.Id == c.Id, "Lecture")).ToList();
            ViewBag.Webminars = shoppingCart.Webminars
                .Select(w => _unitOfWork.Webminar.Get(webminar => webminar.Id == w.Id, "City,Lecture")).ToList();

            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult RemoveFromCart(int itemId, string itemType)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ShoppingCart shoppingCart = _unitOfWork.ShoppingCart.Get(s => s.ApplicationUserId == userId, "Courses,Webminars");

            if (itemType == "Course")
            {
                var courseToRemove = shoppingCart.Courses.FirstOrDefault(c => c.Id == itemId);
                if (courseToRemove != null)
                {
                    shoppingCart.Courses.Remove(courseToRemove);
                }
            }
            else if (itemType == "Webminar")
            {
                var webminarToRemove = shoppingCart.Webminars.FirstOrDefault(w => w.Id == itemId);
                if (webminarToRemove != null)
                {
                    shoppingCart.Webminars.Remove(webminarToRemove);
                }
            }

            _unitOfWork.Save(); // Save changes to the database

            return RedirectToAction("Index");
        }

    }
}

RightPath/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RightPath.Data;
using RightPath.Models;
using RightPath.Repository.IRepository;

namespace RightPath.Controllers
{
    public class CitiesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CitiesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Cities
        public IActionResult Index()
        {
            List<City> objCityList = _unitOfWork.City.GetAll().ToList();
            return View(objCityList);
        }

        // GET: Cities/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(City city)
        {
            if(city.Name == city.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "The DisplayOrder cannot exactly match the Name");
            }

            if (ModelState.IsValid)
            {
                _unitOfWork.City.Add(city);
                _unitOfWork.Save();
                TempData["success"] = "Градът е създаден успешно!";
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Cities/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            City? city = _unitOfWork.City.Get(u => u.Id == id);

            if (city == null)
            {
                return NotFound();
            }
            return View(city);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(City city)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.City.Update(city);
                _unitOfWork.Save();
                TempData["success"] = "Детайлите по градът са променени успешно!";
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Cities/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            City? cityFromDb = _unitOfWork.City
                .Get(u => u.Id == id);
            if (cityFromDb == null)
            {
                return NotFound();
            }

            return View(cityFromDb);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int? id)
        {
            City? obj= _unitOfWork.City.Get(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.City.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Градът е изтрит успешно!";
            return RedirectToAction("Index");
        }
    }
}

RightPath/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]RightPath</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RightPath.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RightPath</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1" style="align-items:center;">
                        <li class="nav-item">
                            <a class="nav-link text-dark" style="padding-right:0;" asp-area="Customer" asp-controller="Home" asp-action="Index">Начало</a>
                        </li>
                        @if (User.IsInRole(StaticDetail.Role_Admin))
                        {
                            <li class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" style="padding-left:0;" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Управлявай Съдържанието
                                </button>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="nav-link dropdown-item text-dark" asp-area="Admin" asp-controller="Courses" asp-action="Index">Курсове</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link dropdown-item text-dark" asp-area="Admin" asp-controller="Webminars" asp-action="Index">Уебминари</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link dropdown-item text-dark" asp-area="Admin" asp-controller="Lectures" asp-action="Index">Лектори</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link dropdown-item text-dark" asp-area="Admin" asp-controller="Cities" asp-action="Index">Градове</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link dropdown-item text-dark" asp-area="Admin" asp-controller="ApplicationUser" asp-action="Index">Менажирай Потребителите</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="ForUs" asp-action="Index">
                                За Нас
                            </a>
                        </li>
                        @if (User.IsInRole(StaticDetail.Role_Customer))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Customer" asp-controller="Cart" asp-action="Index">  
                                    Любими
                                </a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2024 - RightPath - By DivakovDev
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RightPath/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script>
        toastr.success('@TempData["success"]');
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script>
        toastr.error('@TempData["error"]');
    </script>
}