RightPath/Models/Webminar.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RightPath.Models
{
    public class Webminar
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Името е задължително!")]
        [DisplayName("Име на Уебминар")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Описанието е задължително!")]
        [DisplayName("Описание на Уебминар")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Началната дата е задължителна!")]
        [DisplayName("Начална Дата")]
        public DateTime StartDate { get; set; }

        [Required(ErrorMessage = "Локацията е задължителна!")]
        [DisplayName("Локация на Събитието")]
        public int CityId { get; set; }
        [ForeignKey("CityId")]
        [ValidateNever]
        public City City { get; set; }

        [Required(ErrorMessage = "Корицата е задължителна")]
        [DisplayName("Снимка на Уебминара")]
        [ValidateNever]
        public string Logo{ get; set; }

        [Required(ErrorMessage = "Водещият Лектор е задължителен!")]
        [DisplayName("Водещ Лектор")]
        public int LectureId { get; set; }
        [ForeignKey("LectureId")]
        [ValidateNever]
        public Lecture Lecture { get; set; }


        public List<ShoppingCart> Carts { get; set; } = new List<ShoppingCart>();
    }
}

RightPath/Models/Webminars.cs
using System.ComponentModel.DataAnnotations;

namespace RightPath.Models
{
    public class Webminars
    {
        [Key]
        public int WebminarId { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string WebminarDescription { get; set; }

        [Required]
        public DateTime StartDate { get; set; }

        public DateTime EndDate { get; set; }

        [Required]
        public string WebminarLocation { get; set; }

        [Required]
        public string Lecture1 { get; set; } 

        public string Lecture2 { get; set; }
    }
}

RightPath/Areas/Admin/Controllers/WebminarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RightPath.Models.ViewModel;
using RightPath.Data;
using RightPath.Models;
using RightPath.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;

namespace RightPath.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = StaticDetail.Role_Admin)]
    public class WebminarsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public WebminarsController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Webminars
        public IActionResult Index()
        {
            List<Webminar> objCityList = _unitOfWork.Webminar.GetAll(includeProperties: "City,Lecture").ToList();
            return View(objCityList);
        }

        // GET: Webminars/Create
        public IActionResult Upsert(int? id)
        {
            WebminarVM webminarVM = new()
            {
                CityList = _unitOfWork.City.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                LectureList = _unitOfWork.Lecture.GetAll().Select(y => new SelectListItem
                {
                    Text = y.Name,
                    Value = y.Id.ToString()
                }),
                Webminar = new Webminar()
            };

            if(id == null || id == 0)
            {
                //functionality for create
                return View(webminarVM);
            }
            else
            {
                //functionality for edit
                webminarVM.Webminar = _unitOfWork.Webminar.Get(u=> u.Id == id);
                return View(webminarVM);
            }
        }

        [HttpPost]
        public IActionResult Upsert(WebminarVM webminarVM, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                if (webminarVM.Webminar.StartDate < DateTime.Today)
                {
                    ModelState.AddModelError("Webminar.StartDate", "Датата на Уебминара не може да бъде в Миналото!");
                    webminarVM.CityList = _unitOfWork.City.GetAll().Select(u => new SelectListItem
                    {
                        Text = u.Name,
                        Value = u.Id.ToString()
                    });
                    webminarVM.LectureList = _unitOfWork.Lecture.GetAll().Select(y => new SelectListItem
                    {
                        Text = y.Name,
                        Value = y.Id.ToString()
                    });
                    return View(webminarVM);
                }

                string wwwRoothPath = _webHostEnvironment.WebRootPath;
                if(file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string productPath = Path.Combine(wwwRoothPath, @"images\products");

                    if (!string.IsNullOrEmpty(webminarVM.Webminar.Logo))
                    {
                        //delete old image logic
                        var oldImagePath = Path.Combine(wwwRoothPath, webminarVM.Webminar.Logo.TrimStart('\\'));

                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }

                    webminarVM.Webminar.Logo = fileName;
                }

                if(webminarVM.Webminar.Id == 0)
                {
                    _unitOfWork.Webminar.Add(webminarVM.Webminar);
                    TempData["success"] = "Уебминара е създаден успешно!";
                }
                else
                {
                    _unitOfWork.Webminar.Update(webminarVM.Webminar);
                    TempData["success"] = "Уебминара е редактиран успешно!";
                }
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            webminarVM.CityList = _unitOfWork.City.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            webminarVM.LectureList = _unitOfWork.Lecture.GetAll().Select(y => new SelectListItem
            {
                Text = y.Name,
                Value = y.Id.ToString()
            });
            return View(webminarVM);

        }

        // POST: Webminars/Delete/5
        public IActionResult Delete(int id)
        {
            Webminar obj = _unitOfWork.Webminar.Get(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.Webminar.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Уебминара е изтрит успешно!";
            return RedirectToAction("Index");
        }
    }
}

RightPath/Areas/Admin/Views/Webminars/Create.cshtml
@model WebminarVM;

<h1 class="fw-bold">Създай</h1>

<h5>Уебминар</h5>
<hr />
<div class="row justify-content-center">
    <div class="col-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group py-1">
                <label asp-for="Webminar.Title" class="control-label"></label>
                <input asp-for="Webminar.Title" class="form-control" />
                <span asp-validation-for="Webminar.Title" class="text-danger"></span>
            </div>
            <div class="form-group py-1">
                <label asp-for="Webminar.Description" class="control-label"></label>
                <input asp-for="Webminar.Description" class="form-control" />
                <span asp-validation-for="Webminar.Description" class="text-danger"></span>
            </div>
            <div class="form-group py-1">
                <label asp-for="Webminar.StartDate" class="control-label"></label>
                <input type="date" asp-for="Webminar.StartDate" class="form-control" />
                <span asp-validation-for="Webminar.StartDate" class="text-danger"></span>
            </div>
            <div class="form-group py-1">
                <label asp-for="Webminar.CityId" class="control-label ms-2"></label>
                <select asp-for="@Model.Webminar.CityId" asp-items="@Model.CityList" class="form-select">
                    <option disabled selected>--Избери Град--</option>
                </select>
                <span asp-validation-for="Webminar.CityId" class="text-danger"></span>
            </div>
            <div class="form-group py-1">
                <label asp-for="Webminar.Lecture1Id" class="control-label"></label>
                <select asp-for="@Model.Webminar.Lecture1Id" asp-items="@Model.LectureList" class="form-select">
                    <option disabled selected>--Избери Водещ Лектор--</option>
                </select>
                <span asp-validation-for="Webminar.Lecture1Id" class="text-danger"></span>
            </div>
            <div class="form-group py-1">
                <label asp-for="Webminar.Lecture2Id" class="control-label"></label>
                <select asp-for="@Model.Webminar.Lecture2Id" asp-items="@Model.LectureList" class="form-select">
                    <option disabled selected>--Избери Лектор Помощник--</option>
                </select>
                <span asp-validation-for="Webminar.Lecture2Id" class="text-danger"></span>
            </div>
            <div class="form-group py-1">
                <label asp-for="Webminar.Logo" class="control-label"></label>
                <input asp-for="Webminar.Logo" class="form-control" />
                <span asp-validation-for="Webminar.Logo" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Create" class="btn btn-primary btn-md" />
                <a class="btn btn-link btn-md" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RightPath/Areas/Admin/Views/Webminars/Index.cshtml
@using RightPath.Models;
@model IEnumerable<RightPath.Models.Webminar>

<partial name="_Notification" />
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-primary py-2">Уебминари</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Webminars" asp-action="Upsert" class="btn btn-primary shadow">
                    <i class="bi bi-plus-circle"></i> Създай нов Уебминар
                </a>
            </div>
        </div>
        <table id="tblData" class="table table-custom table-striped table-bordered">
            <thead>
                <tr class="text-nowrap">
                    <th>
                        Име
                    </th>
                    <th>
                        Описание
                    </th>
                    <th>
                        Начална Дата
                    </th>
                    <th>
                        Град
                    </th>
                    <th>
                        Лектор
                    </th>
                    <th>
                        Лого
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr style="font-size: smaller;">
                        <td>
                            @item.Title
                        </td>
                        <td>
                            @item.Description
                        </td>
                        <td>
                            @item.StartDate.ToString("dd-MM-yyyy")
                        </td>
                        <td>
                            @item.City.Name
                        </td>
                        <td>
                            @item.Lecture.Name
                        </td>
                        <td>
                            @item.Logo
                        </td>
                        <td>
                            <div class="btn-group badge" role="group">
                                <a asp-controller="Webminars" asp-action="Upsert" asp-route-id="@item.Id" class="shadow btn btn-light mx-2 px-4">
                                    <i class="bi bi-pencil-square"></i> Редактирай
                                </a>
                                <a asp-controller="Webminars" asp-action="Delete" asp-route-id="@item.Id" class="w-8 shadow btn btn-danger mx-2 px-3">
                                    <i class="bi bi-trash-fill"></i> Изтрий
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

RightPath/Areas/Admin/Views/Webminars/Upsert.cshtml
@model WebminarVM;

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-dark py-2"> @(Model.Webminar.Id != 0 ? "Редактирай" : "Създай") Уебминар</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form asp-action="Upsert" enctype="multipart/form-data">
            <input asp-for="Webminar.Id" hidden />
            <input asp-for="Webminar.Logo" hidden />

            <div class="row">
                <div class="col-10">
                    <div class="form-group py-1">
                        <label asp-for="Webminar.Title" class="control-label"></label>
                        <input asp-for="Webminar.Title" class="form-control" />
                        <span asp-validation-for="Webminar.Title" class="text-danger"></span>
                    </div>
                    <div class="form-group py-1">
                        <label asp-for="Webminar.Description" class="control-label"></label>
                        <input asp-for="Webminar.Description" class="form-control" />
                        <span asp-validation-for="Webminar.Description" class="text-danger"></span>
                    </div>
                    <div class="form-group py-1">
                        <label asp-for="Webminar.StartDate" class="control-label"></label>
                        <input type="date" asp-for="Webminar.StartDate" class="form-control" />
                        <span asp-validation-for="Webminar.StartDate" class="text-danger"></span>
                    </div>
                    <div class="form-group py-1">
                        <label asp-for="Webminar.CityId" class="control-label ms-2"></label>
                        <select asp-for="@Model.Webminar.CityId" asp-items="@Model.CityList" class="form-select">
                            <option disabled selected>--Избери Град--</option>
                        </select>
                        <span asp-validation-for="Webminar.CityId" class="text-danger"></span>
                    </div>
                    <div class="form-group py-1">
                        <label asp-for="Webminar.LectureId" class="control-label"></label>
                        <select asp-for="@Model.Webminar.LectureId" asp-items="@Model.LectureList" class="form-select">
                            <option disabled selected>--Избери Водещ Лектор--</option>
                        </select>
                        <span asp-validation-for="Webminar.LectureId" class="text-danger"></span>
                    </div>
                    <div class="form-group py-1">
                        <label asp-for="Webminar.Logo" class="control-label"></label>
                        <input type="file" name="file" class="form-control border-0 shadow" />
                    </div>
                    <div class="row pt-3">
                        <div class="col-6 col-md-3">
                            @if (Model.Webminar.Id != 0)
                            {
                                <button type="submit" class="btn btn-primary btn-md form-control">
                                    Редактирай
                                </button>
                            }
                            else
                            {
                                <button type="submit" class="btn btn-primary btn-md form-control">
                                    Създай
                                </button>
                            }
                        </div>
                        <div class="col-6 col-md-3">
                            <a class="btn btn-link btn-md" asp-action="Index">Назад</a>
                        </div>
                    </div>
                </div>
                <div class="col-2">
                    @if (Model.Webminar.Logo == null)
                    {
                        <p>Все още не сте избрали снимка!</p>
                    }
                    else
                    {
                        <img src="~/images/products/@Model.Webminar.Logo" width="100%" alt="Webminar Logo"
                            style="border-radius:5px; border:1px solid #bbb9b9;" />
                    }
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}