RightPath/Models/Lecture.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace RightPath.Models
{
    public class Lecture
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Името е задължително!")]
        [DisplayName("Име на Лектор")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Описанието е задължително!")]
        [DisplayName("Описание на Лектор")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Профилната снимка е задължителна!")]
        [DisplayName("Профилна Снимка")]
        [ValidateNever]
        public string ProfileImage { get; set; }





    }
}

RightPath/Areas/Admin/Controllers/LecturesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RightPath.Models.ViewModel;
using RightPath.Data;
using RightPath.Models;
using RightPath.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;

namespace RightPath.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = StaticDetail.Role_Admin)]
    public class LecturesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public LecturesController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Webminars
        public IActionResult Index()
        {
            List<Lecture> objLectureList = _unitOfWork.Lecture.GetAll().ToList();
            return View(objLectureList);
        }

        // GET: Webminars/Create
        public IActionResult Upsert(int? id)
        {
            LectureVM lectureVM = new()
            {
                Lecture = new Lecture()
            };

            if (id == null || id == 0)
            {
                //functionality for create
                return View(lectureVM);
            }
            else
            {
                //functionality for edit
                lectureVM.Lecture = _unitOfWork.Lecture.Get(u => u.Id == id);
                return View(lectureVM);
            }
        }

        [HttpPost]
        public IActionResult Upsert(LectureVM lectureVM, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRoothPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string productPath = Path.Combine(wwwRoothPath, @"images\products");

                    if (!string.IsNullOrEmpty(lectureVM.Lecture.ProfileImage))
                    {
                        //delete old image logic
                        var oldImagePath = Path.Combine(wwwRoothPath, lectureVM.Lecture.ProfileImage.TrimStart('\\'));

                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }

                    lectureVM.Lecture.ProfileImage = @"\images\products\" + fileName;
                }

                if (lectureVM.Lecture.Id == 0)
                {
                    _unitOfWork.Lecture.Add(lectureVM.Lecture);
                    TempData["success"] = "Лектора е създаден успешно!";
                }
                else
                {
                    _unitOfWork.Lecture.Update(lectureVM.Lecture);
                    TempData["success"] = "Лектора е редактиран успешно!";
                }
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View();

        }

        // POST: Lectures/Delete/5
        public IActionResult Delete(int? id)
        {
            Lecture? obj = _unitOfWork.Lecture.Get(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.Lecture.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Уебминара е изтрит успешно!";
            return RedirectToAction("Index");
        }

        public IActionResult Details(int lectureId)
        {
            Lecture lecture = _unitOfWork.Lecture.Get(u => u.Id == lectureId);
            return View(lecture);
        }

        [HttpPost]
        [ActionName("Details")]
        public IActionResult DetailsPOST(int id)
        {
            Lecture lecture = _unitOfWork.Lecture.Get(u => u.Id == id);
            return View(lecture);
        }

    }
}

RightPath/Areas/Admin/Views/Lectures/Delete.cshtml
@model RightPath.Models.Lecture

<h1>Delete Page</h1>

<h5>Are you sure you want to delete this Lecture?</h5>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfileImage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfileImage)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger btn-md" /> |
        <a class="btn btn-link btn-md" asp-action="Index">Back to List</a>
    </form>
</div>

RightPath/Areas/Admin/Views/Lectures/Details.cshtml
@model Lecture

<form method="post">
    <input asp-for="@Model.Id" hidden />
    <div class="card shadow border-0 mt-4">
        <div class="card-header bg-secondary bg-gradient text-light py-4">
            <div class="row">
                <div class="col-12 text-center">
                    <h3 class="text-dark text-uppercase">@Model.Name</h3>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="py-3 mx-5 d-flex justify-content-between">
                <div class="col-6 col-md-2">
                    <a asp-action="Index" class="btn btn-outline-primary mb-5 fw-semibold btn-sm text-uppercase">
                        <small>Обратно в Началото</small>
                    </a>
                </div>
                <div class="col-6 col-md-2">
                </div>
            </div>
                <div class="row">
                    <div class="col-12 col-lg-3 offset-lg-1 text-center mb-3">
                        <img src="@Model.ProfileImage" width="100%" class="rounded" />
                    </div>
                    <div class="description-container col-12 col-lg-6 offset-lg-1 d-flex flex-column justify-content-between" style="height:350px">
                        <div>
                            <div class="row my-1">
                                <h5 class="text-secondary" style="text-decoration-line: underline; text-underline-offset: 3px;">Описание</h5>
                                <p>@Model.Description</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

RightPath/Areas/Admin/Views/Lectures/Index.cshtml
@using RightPath.Models
@model IEnumerable<RightPath.Models.Lecture>

<partial name="_Notification" />
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-primary py-2">Лектори</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Lectures" asp-action="Upsert" class="btn btn-primary shadow">
                    <i class="bi bi-plus-circle"></i> Добавяне на Лектор
                </a>
            </div>
        </div>

        <table id="lecturesTable" class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Име</th>
                    <th>Описание</th>
                    <th>Снимка</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.Name
                        </td>
                        <td>
                            @item.Description
                        </td>
                        <td>
                            @item.ProfileImage
                        </td>
                        <td>
                            <div class="btn-group badge" role="group">
                                <a asp-controller="Lectures" asp-action="Upsert" asp-route-id="@item.Id" class="shadow btn btn-light mx-2 px-4">
                                    <i class="bi bi-pencil-square"></i> Редактирай
                                </a>
                                <a asp-controller="Lectures" asp-action="Delete" asp-route-id="@item.Id" class="w-8 shadow btn btn-danger mx-2 px-3">
                                    <i class="bi bi-trash-fill"></i> Изтрий
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

RightPath/Areas/Admin/Views/Lectures/Upsert.cshtml
@model LectureVM;

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-dark py-2"> @(Model.Lecture.Id != 0 ? "Редактирай" : "Създай") Лектор</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form asp-action="Upsert" enctype="multipart/form-data">
            <input asp-for="Lecture.Id" hidden />
            <input asp-for="Lecture.ProfileImage" hidden />
            <div class="row">
                <div class="col-10">
                    <div class="form-group py-1">
                        <label asp-for="Lecture.Name" class="control-label"></label>
                        <input asp-for="Lecture.Name" class="form-control" />
                        <span asp-validation-for="Lecture.Name" class="text-danger"></span>
                    </div>
                    <div class="form-group py-1">
                        <label asp-for="Lecture.Description" class="control-label"></label>
                        <input asp-for="Lecture.Description" class="form-control" />
                        <span asp-validation-for="Lecture.Description" class="text-danger"></span>
                    </div>
                    <div class="form-group py-1">
                        <label asp-for="Lecture.ProfileImage" class="control-label"></label>
                        <input type="file" name="file" class="form-control border-0 shadow" />
                    </div>
                    <div class="row pt-3">
                        <div class="col-6 col-md-3">
                            @if (Model.Lecture.Id != 0)
                            {
                                <button type="submit" class="btn btn-primary btn-md form-control">
                                    Редактирай
                                </button>
                            }
                            else
                            {
                                <button type="submit" class="btn btn-primary btn-md form-control">
                                    Създай
                                </button>
                            }
                        </div>
                        <div class="col-6 col-md-3">
                            <a class="btn btn-link btn-md" asp-action="Index">Назад</a>
                        </div>
                    </div>
                </div>
                <div class="col-2">
                    @if (Model.Lecture.ProfileImage== null)
                    {
                        <p>Все още не сте избрали снимка!</p>
                    }
                    else
                    {
                        <img src="~/images/products/@Model.Lecture.ProfileImage" width="100%" alt="Lecture ProfilePicture"
                             style="border-radius:5px; border:1px solid #bbb9b9;" />
                    }
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}